import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Karlskov Auto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`antialiased text-white font-[roboto]`}>{children}</body>
    </html>
  );
}
